use_frameworks!

platform :ios, '10.0'

target 'JLBlueLink_Example' do
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'MJRefresh'
  pod 'JLBlueLink', :path => '../'

  target 'JLBlueLink_Tests' do
    inherit! :search_paths

    
  end
end
